-- Town Bakery Seed Data
-- Sample data for local development and testing
-- This file populates the database with realistic bakery products

-- Insert sample products
INSERT INTO "Product" ("name", "name_ar", "name_en", "description", "description_ar", "description_en", "price", "currency", "image", "slug", "category", "stock", "ingredients") VALUES
('Chocolate Chip Cookies', 'كوكيز الشوكولاتة', 'Chocolate Chip Cookies', 'Freshly baked cookies loaded with premium chocolate chips', 'كوكيز طازجة محشوة برقائق الشوكولاتة عالية الجودة. ناعمة من الداخل وذهبية مقرمشة من الخارج. مثالية مع كوب القهوة أو الشاي.', 'Freshly baked cookies loaded with premium chocolate chips. Perfectly soft inside with a golden crispy exterior. Perfect with coffee or tea.', 45.0, 'EGP', '/assets/product-1.jpg', 'chocolate-chip-cookies', 'حلويات', 50, '["دقيق", "زبدة", "سكر", "شوكولاتة", "بيض", "فانيليا"]'),
('Classic Croissant', 'كرواسان فرنسي', 'Classic Croissant', 'Traditional French croissant with flaky, buttery layers', 'كرواسان فرنسي تقليدي بطبقات رقيقة وزبدية. مخبوز يومياً ليقدم لك تجربة أصيلة من المخبوزات الفرنسية.', 'Traditional French croissant with flaky, buttery layers. Baked daily for an authentic French pastry experience.', 35.0, 'EGP', '/assets/product-2.jpg', 'classic-croissant', 'معجنات', 40, '["دقيق", "زبدة", "خميرة", "ملح", "سكر"]'),
('Red Velvet Cupcake', 'كب كيك الفانيليا الحمراء', 'Red Velvet Cupcake', 'Decadent red velvet cupcake topped with sweet cream cheese frosting', 'كب كيك فاخر بالفانيليا الحمراء مع طبقة من كريمة الجبن الحلوة. كل قضمة تجلب لك السعادة.', 'Decadent red velvet cupcake topped with sweet cream cheese frosting. Every bite brings joy.', 30.0, 'EGP', '/assets/product-3.jpg', 'red-velvet-cupcake', 'حلويات', 35, '["دقيق", "سكر", "زيت", "بيض", "كاكاو", "فانيليا", "كريمة الجبن"]'),
('Artisan Sourdough Bread', 'خبز العجينة المخمرة', 'Artisan Sourdough Bread', 'Traditional sourdough bread with a tangy flavor and crispy crust', 'خبز تقليدي بالعجينة المخمرة مع نكهة لاذعة وقشرة مقرمشة. مخمر لمدة 48 ساعة للحصول على أفضل نكهة.', 'Traditional sourdough bread with a tangy flavor and crispy crust. Fermented for 48 hours for the best taste.', 65.0, 'EGP', '/assets/product-4.jpg', 'artisan-sourdough-bread', 'خبز', 25, '["دقيق", "ماء", "ملح", "خميرة طبيعية"]'),
('Cinnamon Roll', 'لفائف القرفة', 'Cinnamon Roll', 'Swirled with cinnamon sugar and topped with rich cream cheese icing', 'لفائف معطرة بالقرفة والسكر ومغطاة بطبقة من الجبن الكريمي الحلو. دافئة ولذيذة ولا تقاوم.', 'Swirled with cinnamon sugar and topped with rich cream cheese icing. Warm, gooey, and irresistible.', 32.0, 'EGP', '/assets/product-5.jpg', 'cinnamon-roll', 'حلويات', 30, '["دقيق", "سكر", "قرفة", "زبدة", "كريمة الجبن", "خميرة"]'),
('Lemon Tart', 'فطيرة الليمون', 'Lemon Tart', 'Tart with crispy pastry shell filled with sweet and refreshing lemon cream', 'فطيرة بطبقة عجينة مقرمشة محشوة بكريمة الليمون الحلوة والمنعشة. حلوى مثالية لأيام الصيف.', 'Tart with crispy pastry shell filled with sweet and refreshing lemon cream. Perfect dessert for summer days.', 50.0, 'EGP', '/assets/product-6.jpg', 'lemon-tart', 'حلويات', 20, '["عجينة", "ليمون", "سكر", "بيض", "زبدة", "كريمة"]'),
('Bagel with Sesame', 'خبز الباجل بالسمسم', 'Bagel with Sesame', 'Fresh bagel with sesame seeds, perfect for breakfast', 'خبز باجل طازج مع بذور السمسم، مثالي لفطور الصباح. مقرمش من الخارج وطري من الداخل.', 'Fresh bagel with sesame seeds, perfect for breakfast. Crispy outside and soft inside.', 15.0, 'EGP', '/assets/product-1.jpg', 'bagel-sesame', 'خبز', 60, '["دقيق", "ماء", "خميرة", "سمسم", "ملح"]'),
('Chocolate Eclair', 'إكلير الشوكولاتة', 'Chocolate Eclair', 'Classic French pastry filled with vanilla cream and topped with chocolate', 'معجنات فرنسية كلاسيكية محشوة بكريمة الفانيليا ومغطاة بالشوكولاتة. حلوى فاخرة ولذيذة.', 'Classic French pastry filled with vanilla cream and topped with chocolate. Luxurious and delicious dessert.', 40.0, 'EGP', '/assets/product-2.jpg', 'chocolate-eclair', 'حلويات', 28, '["دقيق", "زبدة", "بيض", "كريمة الفانيليا", "شوكولاتة"]'),
('Whole Wheat Bread', 'خبز القمح الكامل', 'Whole Wheat Bread', 'Healthy whole wheat bread, rich in fiber and nutrients', 'خبز صحي من القمح الكامل، غني بالألياف والعناصر الغذائية. مثالي لصحة أفضل.', 'Healthy whole wheat bread, rich in fiber and nutrients. Perfect for better health.', 55.0, 'EGP', '/assets/product-3.jpg', 'whole-wheat-bread', 'خبز', 35, '["دقيق القمح الكامل", "ماء", "خميرة", "ملح", "عسل"]'),
('Apple Pie', 'فطيرة التفاح', 'Apple Pie', 'Traditional apple pie with cinnamon and brown sugar', 'فطيرة تفاح تقليدية بالقرفة والسكر البني. دافئة ومليئة بالنكهات الطبيعية للتفاح.', 'Traditional apple pie with cinnamon and brown sugar. Warm and full of natural apple flavors.', 70.0, 'EGP', '/assets/product-4.jpg', 'apple-pie', 'حلويات', 15, '["عجينة", "تفاح", "قرفة", "سكر بني", "زبدة"]'),
('Danish Pastry', 'معجنات دانماركية', 'Danish Pastry', 'Buttery, flaky Danish pastry with fruit filling', 'معجنات دانماركية زبدية وطبقات رقيقة مع حشوة الفواكه. مخبوزة طازجة كل يوم.', 'Buttery, flaky Danish pastry with fruit filling. Freshly baked every day.', 38.0, 'EGP', '/assets/product-5.jpg', 'danish-pastry', 'معجنات', 32, '["دقيق", "زبدة", "فواكه", "سكر", "بيض"]'),
('Brioche', 'خبز البريوش', 'Brioche', 'Rich and tender brioche bread, perfect for French toast', 'خبز بريوش غني وطري، مثالي للخبز الفرنسي المحمص. طعم زبدي فاخر.', 'Rich and tender brioche bread, perfect for French toast. Luxurious buttery taste.', 48.0, 'EGP', '/assets/product-6.jpg', 'brioche', 'خبز', 27, '["دقيق", "زبدة", "بيض", "سكر", "خميرة", "ملح"]');

-- Insert sample admin user (optional)
INSERT INTO "User" ("name", "email", "role", "createdAt") VALUES
('Admin User', 'admin@townbakery.com', 'admin', datetime('now')),
('Test Customer', 'customer@example.com', 'customer', datetime('now'));

-- Insert sample contact message (optional)
INSERT INTO "Contact" ("name", "email", "message", "createdAt") VALUES
('أحمد محمد', 'ahmed@example.com', 'أريد أن أسأل عن المنتجات المتوفرة للتوصيل', datetime('now')),
('Sarah Ali', 'sarah@example.com', 'I would like to know about your delivery service', datetime('now'));

